name: Branch Tag Release
on:
  workflow_dispatch:
    branches:
      - main

jobs:
  branch-tag-release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the code
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.AUTO_COMMIT }}
          ref: ${{ github.event.inputs.git_tag }}

      - name: version major
        id: version_major
        uses: christian-draeger/read-properties@1.0.1
        with:
          path: 'app/version.properties'
          property: 'VERSION_MAJOR'
      
      - name: version minor
        id: version_minor
        uses: christian-draeger/read-properties@1.0.1
        with:
          path: 'app/version.properties'
          property: 'VERSION_MINOR'

      - name: version patch
        id: version_patch
        uses: christian-draeger/read-properties@1.0.1
        with:
          path: 'app/version.properties'
          property: 'VERSION_PATCH'

      - name: Setup python 
        id: setup_python 
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8 pytest
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Lint with flake8
        run: |
          # stop the build if there are Python syntax errors or undefined names
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
      
      - name: Test with pytest
        run: |
          pytest
      
      - name: Build the package
        run: |
          python -m build

      - name: Upload packages 
        uses: actions/upload-artifact@v3.1.0
        with:
          name: my-artifact 
          path: dist/* 

      - name: tag name
        id: tag_name
        run: echo "##[set-output name=value;]${{ steps.version_major.outputs.value }}.${{ steps.version_minor.outputs.value }}.${{ steps.version_patch.outputs.value }}"

      - name: tag
        id: tag
        uses: mathieudutour/github-tag-action@v6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          custom_tag: ${{ steps.tag_name.outputs.value }}

      - name: Create Release
        uses: ncipollo/release-action@v1.10.0
        with:
          artifacts: dist/* 
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ steps.tag.outputs.new_tag }}
