name: Branch Patch Version Bump
on:
  workflow_dispatch:
    branches:
      - main

jobs:
  branch-patch-version-bump:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the code
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.AUTO_COMMIT }}
          ref: ${{ github.event.inputs.git_tag }}

      - name: version
        id: version
        run: |
          echo "PACKAGE_VERSION=$(cat pyproject.toml |grep 'version ='|awk -F\= '{print $2}'|awk '{$1=$1;print}'|sed 's/\"//g')" >> $GITHUB_OUTPUT
          echo "PACKAGE_VERSION_MAJOR=$(cat pyproject.toml |grep 'version ='|awk -F\= '{print $2}'|awk '{$1=$1;print}'|sed 's/\"//g'|awk -F\. '{print $1}')" >> $GITHUB_OUTPUT
          echo "PACKAGE_VERSION_MINOR=$(cat pyproject.toml |grep 'version ='|awk -F\= '{print $2}'|awk '{$1=$1;print}'|sed 's/\"//g'|awk -F\. '{print $2}')" >> $GITHUB_OUTPUT
          echo "PACKAGE_VERSION_PATCH=$(cat pyproject.toml |grep 'version ='|awk -F\= '{print $2}'|awk '{$1=$1;print}'|sed 's/\"//g'|awk -F\. '{print $3}')" >> $GITHUB_OUTPUT
      
      - name: new version patch
        id: new_version_patch
        run: echo "NEW_PACKAGE_VERSION_PATCH=$(echo "${{ steps.version.outputs.PACKAGE_VERSION_PATCH }} + 1" | bc)" >> $GITHUB_OUTPUT

      - name: new version
        id: new_version
        run: echo "NEW_PACKAGE_VERSION=$(echo "${{ steps.version.outputs.PACKAGE_VERSION_MAJOR }}.${{ steps.version.outputs.PACKAGE_VERSION_MINOR }}.${{ steps.new_version_patch.outputs.NEW_PACKAGE_VERSION_PATCH }}")" >> $GITHUB_OUTPUT

      - name: Update version in pyproject
        id: update_version
        run: sed -i -E  "s/version = \"${{ steps.version.outputs.PACKAGE_VERSION }}\"/version = \"${{ steps.new_version.outputs.NEW_PACKAGE_VERSION }}\"/" pyproject.toml

      - name: Push new files back to branch.
        uses: stefanzweifel/git-auto-commit-action@v5.0.0
        with:
          commit_message: "#Patch version bump, #skip-ci"
          status_options: '--untracked-files=no'
          disable_globbing: true
